version: "3.4"

services:
  db:
    image: postgres
    container_name: guessthewordapp_pgDb
    restart: always
    environment:
      - POSTGRES_USER=${PG_DB_USERNAME}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
      - TZ=Europe/Lisbon
      - PGTZ=Europe/Lisbon
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5433:5432"

  pgadmin:
    # image: dpage/pgadmin4
    container_name: guessthewordapp_pgAdminContainer
    build: ./pgadmin/
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    volumes:
      # - ./pgadmin-data:/var/lib/pgadmin
      # - ./pgadmin/pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/server.json:/pgadmin4/servers.json

  server:
    build: .
    depends_on:
      - db
    container_name: guessthewordapp_servers
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./ :/home/node/app
    environment:
      NODE_ENV: development
      TZ: Europe/Lisbon
    ports:
      - 3000:3000
    command: "npm start"

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  pgadmin-data:
    driver: local
