version: "3.4"

services:
  db:
    image: postgres
    container_name: guessthewordapp_pgDb
    restart: always
    environment:
      - POSTGRES_USER=guessthewordappPgAdmin
      - POSTGRES_PASSWORD=guessthewordappPgAdminPassword
      - POSTGRES_DB=guessthewordapp_db
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5433:5432"

  server:
    build: .
    depends_on:
      - db
    container_name: guessthewordapp_servers
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./ :/home/node/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: "npm start"

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local
  
  
  
  
  
  
  
  
  
  
    # volumes:
  #   dbdata:
# version: "3.4"

# services:
#   guessthewordapp:
#     image: node:12.18-alpine
#     restart: always
#     working_dir: /home/node/app
#     volumes:
#       - ./ :/home/node/app
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3000:3000
#   command: "npm start"
